# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\"\x1f\n\x0f\x45mbedOneRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x10\x45mbedOneResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"\"\n\x11\x45mbedBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"E\n\x12\x45mbedBatchResponse\x12/\n\nembeddings\x18\x01 \x03(\x0b\x32\x1b.embedding.EmbedOneResponse2\xa2\x01\n\x10\x45mbeddingService\x12\x43\n\x08\x45mbedOne\x12\x1a.embedding.EmbedOneRequest\x1a\x1b.embedding.EmbedOneResponse\x12I\n\nEmbedBatch\x12\x1c.embedding.EmbedBatchRequest\x1a\x1d.embedding.EmbedBatchResponseB#\n\x11\x63om.ytsearch.grpcB\x0e\x45mbeddingProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.ytsearch.grpcB\016EmbeddingProto'
  _globals['_EMBEDONEREQUEST']._serialized_start=30
  _globals['_EMBEDONEREQUEST']._serialized_end=61
  _globals['_EMBEDONERESPONSE']._serialized_start=63
  _globals['_EMBEDONERESPONSE']._serialized_end=97
  _globals['_EMBEDBATCHREQUEST']._serialized_start=99
  _globals['_EMBEDBATCHREQUEST']._serialized_end=133
  _globals['_EMBEDBATCHRESPONSE']._serialized_start=135
  _globals['_EMBEDBATCHRESPONSE']._serialized_end=204
  _globals['_EMBEDDINGSERVICE']._serialized_start=207
  _globals['_EMBEDDINGSERVICE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
