# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import embedding_pb2 as embedding__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """Shared gRPC contract between Python (server) and Java (client).
    Compile for Python:
    python -m grpc_tools.protoc -I proto \
    --python_out=services/embedding \
    --grpc_python_out=services/embedding \
    proto/embedding.proto

    Compile for Java: add protobuf-maven-plugin to pom.xml.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedOne = channel.unary_unary(
                '/embedding.EmbeddingService/EmbedOne',
                request_serializer=embedding__pb2.EmbedOneRequest.SerializeToString,
                response_deserializer=embedding__pb2.EmbedOneResponse.FromString,
                _registered_method=True)
        self.EmbedBatch = channel.unary_unary(
                '/embedding.EmbeddingService/EmbedBatch',
                request_serializer=embedding__pb2.EmbedBatchRequest.SerializeToString,
                response_deserializer=embedding__pb2.EmbedBatchResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """Shared gRPC contract between Python (server) and Java (client).
    Compile for Python:
    python -m grpc_tools.protoc -I proto \
    --python_out=services/embedding \
    --grpc_python_out=services/embedding \
    proto/embedding.proto

    Compile for Java: add protobuf-maven-plugin to pom.xml.

    """

    def EmbedOne(self, request, context):
        """Embed a single text — used for search queries (latency-sensitive).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedBatch(self, request, context):
        """Embed a batch of texts — used by the indexing worker for transcript chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedOne': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedOne,
                    request_deserializer=embedding__pb2.EmbedOneRequest.FromString,
                    response_serializer=embedding__pb2.EmbedOneResponse.SerializeToString,
            ),
            'EmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=embedding__pb2.EmbedBatchRequest.FromString,
                    response_serializer=embedding__pb2.EmbedBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('embedding.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Shared gRPC contract between Python (server) and Java (client).
    Compile for Python:
    python -m grpc_tools.protoc -I proto \
    --python_out=services/embedding \
    --grpc_python_out=services/embedding \
    proto/embedding.proto

    Compile for Java: add protobuf-maven-plugin to pom.xml.

    """

    @staticmethod
    def EmbedOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/EmbedOne',
            embedding__pb2.EmbedOneRequest.SerializeToString,
            embedding__pb2.EmbedOneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/EmbedBatch',
            embedding__pb2.EmbedBatchRequest.SerializeToString,
            embedding__pb2.EmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
